sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dmcgeown/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dmcgeown/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Docketreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-963049332341"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET
  on:
    branch: master