sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dmcgeown/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dmcgeown/docker-react npm run test